"""Backend-only INTERNAL design protocols. No provider SDK/API is implemented."""
from __future__ import annotations
from typing import Protocol

from .contracts import (BackendContext, CheckoutCommand, CloseRequest, OfficialCheckoutHandoff,
    OriginalRefundRef, OriginalTransactionRef, ProviderObservation, QuoteEnvelope, QuoteRequest,
    RefundObservation, RefundRequest, WebhookEnvelope)


class MerchantPort(Protocol):
    def get_quote(self, request: QuoteRequest, context: BackendContext, *, now: int) -> QuoteEnvelope: ...
    def official_checkout_handoff(self, command: CheckoutCommand, context: BackendContext, *, now: int) -> OfficialCheckoutHandoff: ...
    def create_order(self, command: CheckoutCommand, context: BackendContext, *, now: int) -> ProviderObservation: ...
    def query_order(self, original: OriginalTransactionRef, context: BackendContext, *, now: int) -> ProviderObservation: ...


class PaymentPort(Protocol):
    def create_session(self, command: CheckoutCommand, context: BackendContext, *, now: int) -> OfficialCheckoutHandoff: ...
    def query_original(self, original: OriginalTransactionRef, context: BackendContext, *, now: int) -> ProviderObservation: ...
    def close_original(self, request: CloseRequest, context: BackendContext, *, now: int) -> ProviderObservation: ...
    def refund_original(self, request: RefundRequest, context: BackendContext, *, now: int) -> RefundObservation: ...
    def query_refund_original(self, original: OriginalRefundRef, context: BackendContext, *, now: int) -> RefundObservation: ...
    def verify_webhook(self, envelope: WebhookEnvelope, original: OriginalTransactionRef, context: BackendContext, *, now: int) -> ProviderObservation: ...
